### ISSUE TITLE
Installation Error: 

### ISSUE THREAD

**Issue by filipetrocadoferreira** [lucasb-eyer/DeepFried2#80]
pip install --upgrade git+https://github.com/lucasb-eyer/DeepFried2.git
Downloading/unpacking git+https://github.com/lucasb-eyer/DeepFried2.git
  Cloning https://github.com/lucasb-eyer/DeepFried2.git to /tmp/pip-_Qp0Cj-build
  Running setup.py (path:/tmp/pip-_Qp0Cj-build/setup.py) egg_info for package from git+https://github.com/lucasb-eyer/DeepFried2.git

Installing collected packages: DeepFried2
  Found existing installation: DeepFried2 0.01
    Uninstalling DeepFried2:
      Successfully uninstalled DeepFried2
  Running setup.py install for DeepFried2
      File "/home/followinspiration/catkin_ws/pyenv/lib/python2.7/site-packages/DeepFried2/init/Concat.py", line 3
        def concat(*inits, axis=-1):
                              ^
    SyntaxError: invalid syntax

Successfully installed DeepFried2
Cleaning up...

**Comment by lucasb-eyer** [comment]
Thanks. This is because of python2 incompatiblity, I'm mostly using python3. I'm guessing you're using ROS and thus are bound to use python2. You should be able to ignore this error and use most of `DeepFried2` just fine. If not, delete the line `from .Concat import concat` in `DeepFried2/DeepFried2/init/__init__.py`. I'll fix this soon.

**Comment by filipetrocadoferreira** [comment]
Nice! Yes I'm using ROS and I will try your DROW detector with Jetson Tk1/Tx1 and notice you. thanks!

**Comment by lucasb-eyer** [comment]
Cool, hope it will install smoothly! Note that the code in the strands repos is preliminary and we plan to make a full release (with code to train new models) in a bunch of months.

**Comment by filipetrocadoferreira** [comment]
Running DROW from Strands, with CUDA 7-0 in a GTX 680 (yap, lame gpu :( ) i get this

`
$THEANO_FLAGS='cuda.root=/usr/local/cuda-7.0/,floatX=float32,device=gpu0' roslaunch wheelchair_detector drow.launch
`

```
Using gpu device 0: GeForce GTX 680 (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 2000.)
Traceback (most recent call last):
  File "/home/followinspiration/catkin_ws/src/strands_perception_people/wheelchair_detector/scripts/detector.py", line 9, in <module>
    import net
  File "/home/followinspiration/catkin_ws/src/strands_perception_people/wheelchair_detector/scripts/net.py", line 4, in <module>
    import DeepFried2 as df
  File "/home/followinspiration/catkin_ws/pyenv/local/lib/python2.7/site-packages/DeepFried2/__init__.py", line 22, in <module>
    from . import datasets
  File "/home/followinspiration/catkin_ws/pyenv/local/lib/python2.7/site-packages/DeepFried2/datasets/__init__.py", line 5, in <module>
    from . import stanfordbg
  File "/home/followinspiration/catkin_ws/pyenv/local/lib/python2.7/site-packages/DeepFried2/datasets/stanfordbg.py", line 2, in <module>
    from .images import imread
ImportError: No module named images
[detector-1] process has died [pid 32650, exit code 1, cmd /home/followinspiration/catkin_ws/src/strands_perception_people/wheelchair_detector/scripts/detector.py __name:=detector __log:=/home/followinspiration/.ros/log/513784ea-16c8-11e6-bb1f-08606edac62c/detector-1.log].
log file: /home/followinspiration/.ros/log/513784ea-16c8-11e6-bb1f-08606edac62c/detector-1*.log
[detector-1] restarting process
process[detector-1]: started with pid [300]

```

**Comment by filipetrocadoferreira** [comment]
I guess I have to install python3 no?

**Comment by lucasb-eyer** [comment]
No, this is a mistake I introduced in a commit a few days ago, I've already been made aware of it and will fix it ASAP. (I forgot a file in the commit.) In the meantime, you can remove (or comment out) the line `from . import stanfordbg` from the file `DeepFried2/datasets/__init__.py`, it will fix this error and it's not needed to run DROW.

**Comment by Pandoro** [comment]
Please also pay attention to the cudnn warning. If cudnn is too old for the
theano version you use, this will result in theano using the slower
convolutions and then the detector will be slow. Otherwise your GPU should
easily keep up with a 13Hz sick laser scanner. I tested it on a less
powerful GPU and it ran fine, but only with cudnn support.

**Comment by lucasb-eyer** [comment]
Yes, thanks. Since you're using CUDA 7.0, you'll need cuDNN 4.0

Also, the `stanfordbg` issue is now recorded here: #81.

**Comment by lucasb-eyer** [comment]
The second problem (missing `imread`) is now fixed in master. Keeping this issue open because I do want to fix the first one sometime.
